### ISSUE TITLE
detectvideo_counter.py

### ISSUE THREAD

**Issue by byq-luo** [molimat/tcc#1]
Traceback (most recent call last):
  File "detectvideo_counter.py", line 189, in <module>
    app.run(main)
  File "D:\ProgramData\Anaconda3\envs\drone\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "D:\ProgramData\Anaconda3\envs\drone\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "detectvideo_counter.py", line 115, in main
    pred_bbox = utils.postprocess_bbbox(pred_bbox, ANCHORS, STRIDES, XYSCALE)
  File "C:\Users\Administrator\Downloads\Compressed\tcc-d16ccad36f42818bb0dcbe116af70b802ee62f6f\core\utils.py", line 308, in postprocess_bbbox
    xy_grid = np.tile(tf.expand_dims(xy_grid, axis=0), [1, 1, 1, 3, 1])
  File "<__array_function__ internals>", line 6, in tile
  File "D:\ProgramData\Anaconda3\envs\drone\lib\site-packages\numpy\lib\shape_base.py", line 1248, in tile
    c = _nx.array(A, copy=False, subok=True, ndmin=d)
  File "D:\ProgramData\Anaconda3\envs\drone\lib\site-packages\tensorflow_core\python\framework\ops.py", line 736, in __array__
    " array.".format(self.name))
NotImplementedError: Cannot convert a symbolic Tensor (ExpandDims:0) to a numpy array.

**Comment by molimat** [comment]
Hello, actually this file was just a test, i was not aware that someone was seeing it yet. You should use the _newtrack file which is correctly implemented. I will keep working in this and you can follow up right here.

**Comment by byq-luo** [comment]
> Hello, actually this file was just a test, i was not aware that someone was seeing it yet. You should use the _newtrack file which is correctly implemented. I will keep working in this and you can follow up right here.

Thank you for your great work, I am very interested and had followed you.
